name: cached_media
description: Easily cache your media & save bandwidth. You will be able to quickly and easily handle your media into a powerfull widget.
version: 0.9.6+1
homepage: https://github.com/loic-hamdi/cached_media

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: 
  dio: 
  get_storage: 
  path_provider:  # NO WEB SUPPORT
  permission_handler:  # NO WEB SUPPORT
  uuid: 
  visibility_detector: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a.jpeg