// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entity_cached_image_info.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4361056355033444640),
      name: 'CachedImageInfo',
      lastPropertyId: const IdUid(5, 2068806321529620381),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7836743009845662912),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1370282384575515483),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8241355893635612600),
            name: 'cachedImageUrl',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2357429180052223161),
            name: 'fileSize',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2068806321529620381),
            name: 'dateCreated',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 4361056355033444640),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    CachedImageInfo: EntityDefinition<CachedImageInfo>(
        model: _entities[0],
        toOneRelations: (CachedImageInfo object) => [],
        toManyRelations: (CachedImageInfo object) => {},
        getId: (CachedImageInfo object) => object.id,
        setId: (CachedImageInfo object, int id) {
          object.id = id;
        },
        objectToFB: (CachedImageInfo object, fb.Builder fbb) {
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          final cachedImageUrlOffset = fbb.writeString(object.cachedImageUrl);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, imageUrlOffset);
          fbb.addOffset(2, cachedImageUrlOffset);
          fbb.addInt64(3, object.fileSize);
          fbb.addInt64(4, object.dateCreated.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = CachedImageInfo(
              imageUrl: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              cachedImageUrl: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              fileSize:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              dateCreated: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [CachedImageInfo] entity fields to define ObjectBox queries.
class CachedImageInfo_ {
  /// see [CachedImageInfo.id]
  static final id =
      QueryIntegerProperty<CachedImageInfo>(_entities[0].properties[0]);

  /// see [CachedImageInfo.imageUrl]
  static final imageUrl =
      QueryStringProperty<CachedImageInfo>(_entities[0].properties[1]);

  /// see [CachedImageInfo.cachedImageUrl]
  static final cachedImageUrl =
      QueryStringProperty<CachedImageInfo>(_entities[0].properties[2]);

  /// see [CachedImageInfo.fileSize]
  static final fileSize =
      QueryIntegerProperty<CachedImageInfo>(_entities[0].properties[3]);

  /// see [CachedImageInfo.dateCreated]
  static final dateCreated =
      QueryIntegerProperty<CachedImageInfo>(_entities[0].properties[4]);
}
